package com.scottandmarc.opendotareborn.app.domain.entities

data class RecentMatch(
    val matchId: String,
    val playerSlot: Int,
    val radiantWin: Boolean,
    val duration: Int,
    val gameMode: Int,
    val lobbyType: Int,
    val heroId: Int,
    val startTime: Int,
    val version: Int?,
    val kills: Int,
    val deaths: Int,
    val assists: Int,
    val skill: Int?,
    val xpPerMin: Int,
    val goldPerMin: Int,
    val heroDamage: Int,
    val towerDamage: Int,
    val heroHealing: Int,
    val lastHits: Int,
    val lane: Int,
    val laneRole: Int,
    val isRoaming: Boolean,
    val cluster: Int,
    val leaverStatus: Int,
    val partySize: Int?,
)
